### ISSUE TITLE
Make dglOpenGL in the form of a package

### ISSUE THREAD

**Issue by theavege** [PascalCorpsman/sandtris#3]
I want to add Github-Actions.

Could you please make fork from [dglOpenGL](https://github.com/SaschaWillems/dglOpenGL) and make in the form of a package?

**Comment by PascalCorpsman** [comment]
Hello Theavague,
sorry for beeing that rude, but i still don't get whats the benefit of all that action stuff you add to my repositories. The Sandtris Repo is more or less dead, as it was a showcase for the technique and as you could see not changed during the last year, and not planed to be changed. 

In fact i was thinking of deleting the repository in total and merging the code to my miniproject repo as it is really not that much benefit to have a own repo for..

It seems that i am not the only one on Github you create all that PullRequests ( https://github.com/gcarreno/blink-my-duino/pull/2#issuecomment-2460563245 )
And this author also asks the right questions.

What is all that PR for ?
Why do you want to add all that stuff when there is only a action with no outcome ?

**Comment by theavege** [comment]
[FYI](https://github.com/wp-xyz/Hex/pull/5)

[What is all that PR for ?](https://github.com/wp-xyz/Hex/pull/6#issuecomment-2447261791)

>  Why do you want to add all that stuff when there is only a action with no outcome ?

@PascalCorpsman Do you want that I will add action with outcome?

**Comment by PascalCorpsman** [comment]
That is not what i wrote.
Lets recap.
I really think that what you are doing, is with the best will.

Just let me show you my viewpoint:
- A few weeks ago you added this action thing to one of my repositories. After i granted this, you tried to add the same thing for the most of my repositories.
- On my n-tools repository you also changed the folder structure (which i really don't like)
- Now you requesting me to fork others repositories
- In one of your FYI links you spoilered, that you also plan to do something with my ConfigTD project (i work now for more then 10 years on ConfigTD).

=> This all creates workload on my side and also affects the way i publish and share my code.
You are refering to "setup-lazarus" and i think this could be your final goal (but is not mine).

But:
- as far as i understand it, setup-lazarus can only create linux executables.
- i already have a cicd toolchain running on my local machine that builds executables for Windows and Linux and that also works perfectly with the update feature of ConfigTD.

As long as you created PR's that could be a benefit for others (even if i don't need it), this is fine for me. But now it seems, that your PR's are influencing the way i choose to publish my code. With aim for ConfigTD and also FPC_Atomic it could be that this will kill the update features i really worked hard on.

**Comment by theavege** [comment]
Lets recap.

> That is not what i wrote.

English is not my native language.

>  I really think that what you are doing, is with the best will.

Thank you!

>  A few weeks ago you added this action thing to one of my repositories. After i granted this, you tried to add the same thing for the most of my repositories.

I want to help spread the DevOps culture among Pascale developers.

> On my n-tools repository you also changed the folder structure (which i really don't like)

New folder structure is option. You can refuse it like [there](https://github.com/wp-xyz/Lissajous/pull/1).

> Now you requesting me to fork others repositories

I thought you might be interested in this.

> In one of your FYI links you spoilered, that you also plan to do something with my ConfigTD project (i work now for more then 10 years on ConfigTD).

I don't want to do anything with ConfigTD because it is difficult for me.

>  You are refering to "setup-lazarus" and i think this could be your final goal (but is not mine).

I don't suggest "setup-lazarus" because it's not my project. I think its author can offer his solution better than me. I hope he does so.

> as far as i understand it, setup-lazarus can only create linux executables.

Better ask @gcarreno

> I already have a cicd toolchain running on my local machine that builds executables for Windows and Linux and that also works perfectly with the update feature of ConfigTD.

I'd be glad to see them.

> As long as you created PR's that could be a benefit for others (even if i don't need it), this is fine for me. But now it seems, that your PR's are influencing the way i choose to publish my code. With aim for ConfigTD and also FPC_Atomic it could be that this will kill the update features i really worked hard on.

I don't want to do anything with FPC_Atomic because it is difficult for me.

**Comment by gcarreno** [comment]
Hey Uwe(@PascalCorpsman),

I'm not gonna butt in between you and Artem, but I will demystify the knowledge that you have with `setup-lazarus`.

When I decided to create `setup-lazarus` my intentions were for it to run on all 3 of the platforms that GitHub provides runners for. This means it runs and creates binaries for Windows, Linux and `macOS`, **natively**.
It installs Lazarus on all three from the install media provided by Source Forge and it runs `lazbuild` from a natively compiled binary, itself, ensuring that all the resulting executable binaries are native to the OS that the runner is hosted on.

I'm not quite sure how you got the impression that it only produced Linux binaries, but that's false. And you can possibly attest for it since the Castle Game Engine actually uses it for their `CI`/`CD` here on GitHub.

If you look at [Lazarus with GitHub actions](https://github.com/gcarreno/lazarus-with-github-actions), you'll see that I use the `matrix` trick for all 3 platforms and various versions of Lazarus.

On some of my projects I provide natively compiled binaries when I do a release. While I do tend more towards Linux and Windows when `GUI` is involved, mainly because I don't have a Mac to test those, I also have a tendency to make sure a `macOS` binary is provided when I do `CLI` only, since these are easier not to mess up when ran on the `macOS` terminal.

Hope this cleared some of your doubts.

Cheers,
Gus

**Comment by theavege** [comment]
@gcarreno Thank you.

**Comment by PascalCorpsman** [comment]
Thank you both for clearification.

> I want to help spread the DevOps culture among Pascale developers.
Well then i need to learn if that culture meets my publish / release policies :).

> I thought you might be interested in this.
I already use dglOpenGL.pas but i do not see a reason to create a fork of it.

> I'd be glad to see them.
As you maybe figured out i have a huge codebase on my private git repository (around 1.25M LOC, with more than 3k projects). I only share a view of them to the public, as it is really time consuming to cleanup all the code, insert all the copyright things and polish everything to be published in a usefull way.

Normaly i do not want to share binaries, because Lazarus is free and all the used components are free available (also i share links to all needed components) or give guidelines what needs to be done to compile the code. So in my opinion if someone is interested in my stuff he/she shall compile the code by him/herself.

On some rare projects i decided to share binaries as well, e.g. ConfigTD, FPC_Atomic, ALT_F2, PixelEditor.. i do this because here, i think, that the users are not interested in the code, but more in using the application and maybe not willing to install everything needed.

To provide the binaries i use a docker image from https://github.com/ChrisWiGit/lazarus-docker which is able to crosscompile and fit all my needs. After that i use custom shell scripts to upload everything to github (this makes publishing / updating all my projects a one click action). The other big advantage is that projects like FPC_Atomic, CCM or ConfigTD bring their own auto update infrastructure that can be integrated into my scripts. Finally i want to decide when a new release is made (and not a time or commit based scedule). As i normally do not use the HTML page of github i am now able to do all that work on my local machine. 

As far as i understood the "actions", they do the exact opposite of my needs (compiling the code on scedule or commit), also the "dependabot" seems to check some dependencies, don't know what this shall be good for.

=> 
I should learn more about "actions" and understand this, as far as i understand @gcarreno's explanations the lazarus-with-github-actions then maybe could be really usefull. But if i will use it in the end is still a open question as my process as described above is already really simple and relaible.
So be prepared that it will take some time for me to learn all that and then decide what to do..

**Comment by gcarreno** [comment]
Hey Uwe(@PascalCorpsman),

I completely understand that you got comfortable in your methods and that you don't want to abandon them. That makes a lot of sense.

My goal with `setup-lazarus` was to enable `CI`/`CD` all centred around GitHub actions.

On every commit( the `CI` part ), the actions compile both the Unit Test app and the app itself and run the Unit Test app in order to see if all is good. And sure, not all apps have Unit Tests, but you can make sure that it compiles under the 3 platforms and with various Lazarus versions.

Upon pushing a tag (e.g. `git tag -a v0.0.1 -m "MyApp v0.0.1"; git push --tags`), the actions will automatically produce a new release with compiled binaries to accompany it( the `CD` part ). I even use `git-cliff` to aid me in generating a nice release note with all the commit messages included.

That's my methodology, and I'm not trying to forcibly push it to everyone. If someone has a better methodology, then they should use their own.

Cheers,
Gus

**Comment by PascalCorpsman** [comment]
@gcarreno 
thanks for that notes, i think i will try out setup-lazarus and all the fancy things you descriped, with sandtris, to learn all that stuff and at least have a example which works. After that i hopefully know enough about it to decide if i roll out all that to my other projects. By the way is there a way which i could "test" all that on my local machine or is it plan to always push everything to github and see whether it will pass or not (and if so, where is the log ?)

@theavege 
This means, that i will not fork dglopengl.pas, but will merge your pull request to have a startingpoint.

Target in the end run will be to
- run unittests (they do not exist right now, but i will create some ;) )
- create releases when commiting tags

As i am not shure if it is possible to comment on closed issues, i will leave that one open in case one of you want to reply or have other suggestions..

**Comment by gcarreno** [comment]
Hey Uwe(@PascalCorpsman),

> is there a way which i could "test" all that on my local machine

There's a project that allows you to run GitHub actions locally. I've never tested it myself, so I have no idea how it works: https://github.com/nektos/act

> is it plan to always push everything to github and see whether it will pass or not 

That's what I usually do. I run my Unit Tests locally and then push every commit to GitHub and cross my fingers :wink: 

> where is the log ?

All the run groups are under the `Actions` tab at the top, Each run then has logs for all the individual runs inside a group run.

Cheers,
Gus

**Comment by theavege** [comment]
> As i am not shure if it is possible to comment on closed issues, i will leave that one open in case one of you want to reply or have other suggestions..

@PascalCorpsman It is possible to comment on closed issues

**Comment by gcarreno** [comment]
Hey Uwe(@PascalCorpsman),

Just an addendum to what I said about the `act` app to run GitHub workflows locally:
Just remember that you **ARE** running them locally. This means you're running them on your machine, with all that you have set up in it. Then remember that the GitHub runners are a single pre made image that is used for every run. That image does not contain much of anything Pascal related and you need to make it so by yourself. Also, you'll just be running the actions for your own OS, I think... 

Maybe `act` uses containers and that would make it a bit more like what happens on GitHub... 

But like I said before, I never used `act`, so I'm not fully aware of it's methods to run GitHub workflows locally.

Hope I didn't confused you with this, and I also hope it helps!!

Cheers,
Gus

**Comment by PascalCorpsman** [comment]
@gcarreno 
confusing is good, that enables to learn something new ;). As you could see i already created the test application with a trivial test. Next step will be integrating all this into your suggested setup-lazarus thing. But i thing this will happen after christmas ..

**Comment by gcarreno** [comment]
Hey Uwe(@PascalCorpsman),

That's good to see!!

I wish you all the luck with it !!

Cheers,
Gus
